services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: engrleaks-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: engrleaks-frontend
    working_dir: /app
    command: >
      sh -c "
      npm install && \
      npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

networks:
  default:
    driver: bridge
