# Generated by Django 5.2 on 2025-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGRBackend', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='learned_lesson',
            field=models.JSONField(default=list),
        ),
    ]
