# Generated by Django 5.2 on 2025-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGRBackend', '0004_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='Unenroll', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='total_exercises',
            field=models.IntegerField(default=0),
        ),
    ]
