# Generated by Django 5.2 on 2025-05-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENGRBackend', '0006_enrollment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
