# Generated by Django 5.2 on 2025-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGRBackend', '0007_remove_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='learned_lesson',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
